const ACTION_TYPES = {
  AUTH: {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
  },

  USER: {
    // User's personally identifiable information.
    FILL_PII: 'FILL_PII',
    RESET_PII: 'RESET_PII',
  },

  STUDENTS: {
    GET_STUDENTS: 'GET_STUDENTS',
    GET_STUDENT: 'GET_STUDENT',
    CREATE_STUDENT: 'CREATE_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
  },

  SESSION: {
    // Unique entity comprised of a student and an interview.
    CREATE_SESSION: 'CREATE_SESSION',
    DELETE_SESSION: 'DELETE_SESSION',
    EDIT_SESSION: 'EDIT_SESSION',
  },

  INTERVIEWS: {
    GET_INTERVIEWS: 'GET_INTERVIEWS',
    GET_INTERVIEW: 'GET_STUDENT',
    CREATE_INTERVIEW: 'CREATE_STUDENT',
    DELETE_INTERVIEW: 'DELETE_STUDENT',
  },
};

export default ACTION_TYPES;
